version: '3.8'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/backend
      - /var/run/docker.sock:/var/run/docker.sock
    command: uvicorn api:app --reload --workers 1 --host 0.0.0.0 --port 8000
    env_file:
      - .env
    ports:
      - 8000:8000